### ISSUE TITLE
Viewing DAOs (no account)

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#405]
## Overview 
The current Fallback Provider would allow allow users to search for `mainnet` or `Goerli`. So those DAOs that are created on other networks wouldn't be able to viewed at all without a wallet being connected. probably not a big deal now. but it would be a blocker

## Tasks
- [ ] (MAJOR) Since we support (will support) multiple networks, we should have a way to change the network of the fallback when looking up DAOs. 
- [ ] Disable buttons to create new Proposal
- [ ] Disable Delegate button or redirect on navigation
- [ ] Hide DAO Summary CTA
- [ ] Disable create DAO button
- [ ] remove conditional from DAOController

**Comment by Da-Colon** [comment]
This was discuss some today.

- [ ] Instead of a manually selecting and changing network, search networks for valid DAOs. 
- [ ] if wallet connected and address is found on different network, prompt user to switch networks
- This will involve changes to how the app is 'connected', to show data from another network will have to use the provider for that network, overriding the connected wallet's network until it matches the DAOs network

**Comment by adamgall** [comment]
> This was discuss some today.
> 
> * [ ]  Instead of a manually selecting and changing network, search networks for valid DAOs.
> * [ ]  if wallet connected and address is found on different network, prompt user to switch networks
> * This will involve changes to how the app is 'connected', to show data from another network will have to use the provider for that network, overriding the connected wallet's network until it matches the DAOs network

AFAIK we didn't make any decisions today that this functionality needs to be supported. We were just talking about different options. The above items generally make sense from an engineering point of view, but they should go through the product/design team with more rigor first.

**Comment by Da-Colon** [comment]
Thanks you for the added context.
